### ISSUE TITLE
Can not detect bug of double hight

### ISSUE THREAD

**Issue by Faha98** [malihu/page-scroll-to-id#15]
![detect](https://user-images.githubusercontent.com/11594042/28732555-abd87efe-73f1-11e7-92ad-27f266b5bb4c.png)
Plugin is great, it is really precise when scrolling to section, however i have met a bug, when intersect 2 sections, there are two highlights in menu, but when call Chrome Dev tools, it simly disappears.
![image](https://user-images.githubusercontent.com/11594042/28732686-3c9d587e-73f2-11e7-8ad9-7f405786f66a.png)

What can cause that?, and how can i help to solve this bug?
JS Code
`$("a[rel='m_PageScroll2id']").mPageScroll2id({
	highlightClass:"link-highlight",
});`
HTML code
`<ul class="menu" id="topNav">
	<li><a href="#sec-1" rel="m_PageScroll2id">Главная</a></li>
	<li><a href="#sec-2" rel="m_PageScroll2id">Работа</a></li>
	<li><a href="#sec-3" rel="m_PageScroll2id">Навыки</a></li>
	<li><a href="#sec-4" rel="m_PageScroll2id">Контакты</a></li>
</ul>`
And by css adding simple border bottom.

**Comment by malihu** [comment]
This is not a bug. The highlight feature is completely user-centric, meaning if enough portion of the section is visible on the viewport, its link gets highlighted. 

In your case, when dev tools are closed, both sections are considered visible on the viewport (you can see a good portion of both sections), thus both links are highlighted. 
When dev tools are opened, viewport height gets shorter so only the first section is considered visible (you can only see the title of the second one), so only the first link is highlighted.

If you don't want multiple (e.g. two) links highlighted, see the following faq: 
http://manos.malihu.gr/page-scroll-to-id/3/#faq-11

**Comment by Faha98** [comment]
Thank you very much malihu for such quick respond. 
Hm, very interesting sollution to make by default multiple highlighting. Next time i should check first all available faq and docs.

**Comment by malihu** [comment]
You're welcome :)
