### ISSUE TITLE
Salient Theme Issue

### ISSUE THREAD

**Issue by tcf909** [malihu/page-scroll-to-id#18]
Hello,

I'm currently using the Salient theme and noticed there are a couple of issues:

1) When the salient "one page scroll support" (http://themenectar.com/docs/salient/theme-options/general-settings/#functionality) is enabled when I click a menu it will scroll to the desired location then jump back to the original location.

2) If I disable "one page scroll support"in Salient the links no longer work at all (but the highlighting does).

I tried enabled an disabling every setting you offer to see what affected the outcomes. Nothing worked. (including prevent other scripts from handling links)

To work around the issue I've left the salient functionality enabled and used "#do_not_select" for the primary selector for page-scroll-to-id then used your default selector for the highlight-selector.

Not ideal as I would like all of the functionality page-scroll-to-id offers, but it's the only way I could get Salient and page-scroll-to-id working together.

Any thoughts / suggestions would be appreciated.

Site I'm using this on: https://www.digitalspaces.app/documentation/

Also, using the latest development release (downloaded from wordpress) as of today, and jQuery 3.3.1

**Comment by malihu** [comment]
Hello, 

I can't really provide an exact solution because I'd need to see your page (the link you posted is under construction). 

Normally, you should disable "one page scroll support" and enable "Page scroll to id" on your links. The easiest way to enable the plugin on your links is go to "Page scroll to id" settings and set the "Selector(s)" option to: 

`a[href*='#']:not([href='#'])`

What happens when you disable "one page scroll support" and deactivate "Page scroll to id"? Do the links work?

**Comment by tcf909** [comment]
I went ahead and disabled the under construction mode temporarily.

Attempting your suggestion now.

**Comment by tcf909** [comment]
With the theme feature and the page-scroll plugin both disabled the links do still go to the correct divs (but no scrolling animation).

**Comment by tcf909** [comment]
Actually I created a private link to view the site:

https://www.digitalspaces.app/?ucp-access=4f4e40fb

**Comment by malihu** [comment]
OK, activate "Page scroll to id" and keep "one page scroll support" disabled, so I can check what happens.

**Comment by tcf909** [comment]
Enabled.

**Comment by malihu** [comment]
You've set the "Offset" option value to `.main-content` which is the overall page wrapper. That's why the page doesn't seem to scroll (it's like setting the offset to be 3000 pixels). 

Go to plugin settings and change the "Offset" option to: 

`#header-outer`

which is your top sticky header. 

Save changes and test your page. Everything should work. 

Let me know

**Comment by tcf909** [comment]
same issue.

I noticed if I click the link multiple times it inches down the page. I've also set a value of 120 and same issue.

**Comment by tcf909** [comment]
I also just enabled "scroll from/to" and "enable on all links" and the inching toward the link behavior stopped entirely.

**Comment by tcf909** [comment]
Just want to confirm. 

Even with the change to offset, still having the same issue.

Appreciate your involvement.

**Comment by malihu** [comment]
No problem :) 

Can you reset the plugin options to default? In plugin settings click "Reset to default" button at the bottom.

**Comment by tcf909** [comment]
Done.

**Comment by tcf909** [comment]
I have a slack space setup if your interested in realtime troubleshooting:

https://join.slack.com/t/mydigitalspaces/shared_invite/enQtNTY5MTc0NjM3MDc3LTY4M2RkZGNhY2NiYTQyNDYzY2M4NGYzNWM2Y2U3YTA0MGRlOTAwNmE2YWIwNWFjZDMwOTM1NDdiMzc2MTNjMTg

**Comment by malihu** [comment]
Is it possible that there's some issue with the theme? I noticed that the back to top icon (right-bottom of the page) does not work. It seems to scroll the page up by few pixels each time (same as clicking the menu links). 

This button seems to work in Salient theme docs (http://themenectar.com/docs/salient/) but in your page it doesn't work (it's the exact same button). This button is not handled by "Page scroll to id" in any way, which makes me think that the theme does something weird when "one page scroll support" is disabled(?) 

Maybe the theme doesn't allow page scrolling via other js scripts(?) Can you contact the theme devs and ask them?

**Comment by tcf909** [comment]
I have a ticket opened with them as of this morning:

https://themenectar.ticksy.com/ticket/1932255

I'll keep this ticket updated with what they say.

**Comment by malihu** [comment]
OK. Also, as a test, can you temporarily disable the `mystickysidebar` plugin?

**Comment by tcf909** [comment]
Disabled. Still no change it appears.

**Comment by malihu** [comment]
ok

**Comment by tcf909** [comment]
Ok so I disabled jquery updater and it appears to be working.

**Comment by tcf909** [comment]
Your plugin as well.

**Comment by malihu** [comment]
Oh awesome :) 

What in God's name does  jquery updater do? I've tested the plugin with jQuery 3.3.1 and it works... I'm gonna do some tests again with jquery updater plugin to see what happens.

**Comment by tcf909** [comment]
I'm not all that familiar with it. Was just looking for an easy way to update jquery as part of my troubleshooting.

I hit the bug where the selector isn't properly quoted earlier in the troubleshooting process.

Really appreciate you taking the time.

**Comment by tcf909** [comment]
Dropped a small donation in your account. Thanks again.

**Comment by malihu** [comment]
Thank you!
