### ISSUE TITLE
Wordpress error 

### ISSUE THREAD

**Issue by StudioRATATA** [malihu/page-scroll-to-id#22]
Hi, in the WP version I get this warning after activating:
` Warning: Array to string conversion in /my-path/wp-includes/pluggable.php on line 2292`
`wp 6.2.2.`

**Comment by malihu** [comment]
Hi, 

Please see this post: 

https://wordpress.org/support/topic/twp-includespluggable-php-on-line-2292/#post-16813375

This is a PHP warning (not error) and will be fixed in the next version release. 

Plugin’s development version: 

https://downloads.wordpress.org/plugin/page-scroll-to-id.zip
