### ISSUE TITLE
Scroll not working on live site

### ISSUE THREAD

**Issue by joewellmade** [malihu/page-scroll-to-id#6]
Hi, the scrolling was working fine in development on my local server, however now i've migrated the site the scrolling has stopped, it just jumps to the right section, if I enable on 'scroll to location hash' it works but takes me back to top first every time but with the animated scroll. Link to site: www.buyers-club.co.uk

Do you know what could be happening / not happening?

Thanks,
Joe

**Comment by joewellmade** [comment]
The links aren't working in Safari either?

**Comment by malihu** [comment]
The links seem to be working now... did you fixed it? 

Also, make sure the links URL matches the actual URL. For example, the link on your logo is: 
`http://www.buyers-club.co.uk/#section-one`
when it should be: 
`http://buyers-club.co.uk/#section-one`
because your server does not use `www`.

**Comment by joewellmade** [comment]
Hi, thanks, yeah, I realised this before when reading something else online. Thanks for getting bak to me!

**Comment by malihu** [comment]
Yeah I saw the wordpress support thread after I replied here. No problem :)
