### ISSUE TITLE
Update for jQuery 3

### ISSUE THREAD

**Issue by CreativeNative** [malihu/page-scroll-to-id#8]
Are there any plans to update this really cool plugin for jQuery 3. Unfortunately it doesn't work with jQuery  >= 3.

**Comment by malihu** [comment]
Of course. I'll post a new release asap (today or tomorrow). 
Thanks for the feedback!

**Comment by malihu** [comment]
I've just released [vesrion 1.5.5](https://github.com/malihu/page-scroll-to-id/releases). Try it and let me know.

**Comment by CreativeNative** [comment]
It works like a charm. Thank you for the quick help. Really awesome!
